# Generated by Django 2.1 on 2018-08-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 21, 0, 4, 7, 932390), null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('used', models.CharField(blank=True, max_length=20, null=True)),
                ('un_used', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('port', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('encryption', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login', models.CharField(blank=True, max_length=20, null=True)),
                ('last_check_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
