# Generated by Django 2.1 on 2018-08-14 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpninfo',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 14, 21, 24, 21, 24417), null=True),
        ),
        migrations.AlterField(
            model_name='vpninfo',
            name='last_check_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vpninfo',
            name='last_login',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
